# Generated by Django 6.0.6 on 2026-06-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('current_stock', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('quantity_sold', models.PositiveIntegerField(default=1)),
                ('sale_type', models.CharField(choices=[('MRP', 'MRP'), ('Sample', 'Sample'), ('50%', '50% Discount'), ('Other', 'Other')], default='MRP', max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_in', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplier', models.CharField(default='Dr. Susshil', max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='stock.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
