# Generated by Django 6.0.6 on 2026-06-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distributor Price - can be changed by admin anytime', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed MRP (Maximum Retail Price) of the product', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_base',
            field=models.CharField(choices=[('MRP', 'Discount on MRP'), ('DP', 'Discount on DP (Distributor Price)'), ('NONE', 'No Discount (Full Price)')], default='NONE', help_text='Choose whether discount applies on MRP or DP', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage e.g. 20 for 20% off', max_digits=5),
        ),
    ]
