# Generated by Django 6.0.6 on 2026-07-02 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_dp_product_mrp_sale_discount_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(help_text='City or area e.g. Nerul, Thane, Panvel', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='dp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distributor Price - editable anytime', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed MRP (Maximum Retail Price)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_base',
            field=models.CharField(choices=[('MRP', 'Discount on MRP'), ('DP', 'Discount on DP (Distributor Price)'), ('NONE', 'No Discount (Full Price)')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stock.branch'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='stock.branch'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Branch Manager'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for Owner (owner sees all branches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='stock.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
