# Generated by Django 6.0.6 on 2026-07-03 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_branch_alter_product_dp_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_type', models.CharField(choices=[('branch', 'Company Branch'), ('franchise', 'Franchise')], default='branch', max_length=20)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage of Sales (%)'), ('fixed', 'Fixed Amount per Month (₹)')], default='percentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, help_text='Enter % value (e.g. 10 for 10%) or fixed ₹ amount per month', max_digits=10)),
                ('effective_from', models.DateField(blank=True, default=None, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_setting', to='stock.branch')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_type', models.CharField(default='percentage', max_length=20)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='stock.branch')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('branch', 'month', 'year')},
            },
        ),
    ]
