# Generated by Django 6.0.6 on 2026-07-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_commissionsetting_monthlycommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionsetting',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Service charge % added to commission (e.g. 5 for 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionsetting',
            name='tds_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TDS percentage deducted from commission (e.g. 10 for 10% TDS)', max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='base_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='gross_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='service_charge_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='tds_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlycommission',
            name='tds_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlycommission',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Net payable commission after TDS and service charge', max_digits=12),
        ),
    ]
