# Generated by Django 6.0.6 on 2026-07-10 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_commissionsetting_service_charge_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='account_holder',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='branch',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Branch email for payout notifications', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='Branch mobile for SMS alerts', max_length=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text='UPI ID for direct transfer', max_length=100),
        ),
        migrations.CreateModel(
            name='PayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email + SMS')], default='both', max_length=10)),
                ('sent_to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sent_to_mobile', models.CharField(blank=True, default='', max_length=15)),
                ('email_status', models.CharField(default='pending', max_length=20)),
                ('sms_status', models.CharField(default='pending', max_length=20)),
                ('message_preview', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('monthly_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_logs', to='stock.monthlycommission')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
