# Generated by Django 6.0.7 on 2026-07-15 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_branch_account_holder_branch_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='bank_details_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='bank_details_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='gpay_mobile',
            field=models.CharField(blank=True, default='', help_text='Google Pay mobile number', max_length=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='payment_link',
            field=models.URLField(blank=True, default='', help_text='PayTM/Razorpay/Google Pay payment link'),
        ),
        migrations.AddField(
            model_name='branch',
            name='paytm_mobile',
            field=models.CharField(blank=True, default='', help_text='PayTM mobile number', max_length=15),
        ),
        migrations.AddField(
            model_name='branch',
            name='phonepe_mobile',
            field=models.CharField(blank=True, default='', help_text='PhonePe mobile number', max_length=15),
        ),
    ]
